export default {
    Orange: "#FA6230",
    neural: "#D2D3D3",
    background: "#F6F6F6",
    GREen: "#D2D3D3",
    Textcolor: "#1F2223",
    white: "#FFFFFF",
    neuralblack: "#444748",
    neural200: '#B4B5B6',
    Gobackicon: "#1C1B1F",
    Imagecolor: "#FEE0D6",
    neural400: "#6A6C6C",
    neural800: "#36474F",
    flutter:"#009400",
    textgreen:"#2EAE4E"


}

export const Slid = [
    {id:1,
        title:"Welcome to CyberX",
      description: "Your gateway to seamless bitcoin and git card trading.Where transactions are swift and secure",
      click :"Get Started"
    },
    {
        id:2,
      title: "Trade asserts with ease",
      description:"Choose your trade:cryptocurrency or gitcards and enjoy the best rate",
      click :'Get Started',
    },
    {id:3,
      title: "We secure your assets",
      description:"Security is our priority,safeguarding your assets",
      click :'Get Started',
    },
   
  ];








  

export const print={
    category:"Category",
    data:[{
      id:1,
       shoetype:"Pay Bills",
       Quickactions:"Send",
       date:"Today at 12:15am",
       Dollars:"$16,000.00",
title:"Veonard Victor",
recieved:"Recieved",
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
Cart:"Add to Cart",
Instock :true,
price:"-₦10,000",
btcprice:"+0.06516 BTC",
Status:"Successful",
 icon:"star", 
 icon1:"star",
 icon2:"star",
 icon3:"star",
 icon4:"star",
 sizes:"S",
 sizem:"M",
sizel:"L",
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
recipient:"ox321dd63ty56ee...5tyf4bn",
 wishlist:"love",
 "image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]

},
  {id:2,
   shoetype:"Buy Airtime",
    date:"Today at 12:15am",
    Dollars:"$16,000.00",
    
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
    Cart:"Add to Cart",
Instock :true,
Quickactions:"Recieve",
recieved:"Sent",
btcprice:"-0.06556 ETH",
price:"₦10,000",
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
title:"Flutter Deposit",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
wishlist:"love",
recipient:"ox321dd63ty56ee...5tyf4bn",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
  {id:3,
    shoetype:"Buy Crypto",
   
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
    Cart:"Add to Cart",
date:"Today at 12:15am",
Dollars:"$16,000.00",
Quickactions:"Sell",
recieved:"Recieved",
btcprice:"+0.06516 BTC",
Status:"Successful",
Instock :true,
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
wishlist:"love",
price:"-₦10,000",
title:"Veonard Victor",
 icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
recipient:"ox321dd63ty56ee...5tyf4bn",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
 },
  {id:4,
    shoetype:"Save",
   
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
    Cart:"Add to Cart",
Instock :true,
date:"Today at 12:15am",
Dollars:"$16,000.00",
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
Quickactions:"Convert",
recieved:"Sent",
wishlist:"love",
price:"₦10,000",
btcprice:"-0.06556 ETH",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Flutter Deposit",
recipient:"ox321dd63ty56ee...5tyf4bn",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
{id:5,
  "shoetype":"boot",
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
  Cart:"Add to Cart",
date:"Today at 12:15am",
Dollars:"$16,000.00",
Instock :true,
wishlist:"love",
price:"-₦10,000",
icon:"star",
sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Veonard Victor",
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
Quickactions:"Convert",
btcprice:"+0.06516 BTC",
Status:"Successful",
recieved:"Recieved",
recipient:"ox321dd63ty56ee...5tyf4bn",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
{id:6,
  "shoetype":"boot",
  description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
  Cart:"Add to Cart",
  Instock :true,
 wishlist:"love",
description:"TRF",
Charges:"₦50.00",
transactionref:"09489303423588389",
recipientnaira:"Leonard victor (wema bank)",
 date:"Today at 12:15am",
 Dollars:"$16,000.00",
price:"₦10,000",
icon:"star",

sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Flutter Deposit",
time:"jan 30, 2024",
btcptime:"6th feb, 2024",
Quickactions:"Convert",
btcprice:"-0.06556 ETH",
recieved:"Sent",
recipient:"ox321dd63ty56ee...5tyf4bn",
 "image":require("../image1/image8-2.webp"),
 "image1":require("../image1/image8-2.webp"),
 "image2":[require("../image1/image8-2.webp"),
 require("../image1/image8-2.webp"),
 require("../image1/image8-2.webp"),]
},

],
 }

