

export const print={
    category:"Category",
    data:[{
      id:1,
       shoetype:"Pay Bills",
       Quickactions:"Send",
title:"Veonard Victor",
status:"color",
description:"Did a project design today. never thought i would ever develop much patience .",
Cart:"Add to Cart",
Instock :true,
price:"-₦10,000",
 icon:"star", 
 icon1:"star",
 icon2:"star",
 icon3:"star",
 icon4:"star",
 sizes:"S",
 sizem:"M",
sizel:"L",
time:"jan 30, 2024",
 wishlist:"love",
 "image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]

},
  {id:2,
   shoetype:"Buy Airtime",
    status:"color",
    description:"Did a project design today. never  thought i would ever develop much patience .",
Cart:"Add to Cart",
Instock :true,
Quickactions:"Recieve",
price:"₦10,000",
time:"jan 30, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
title:"Flutter Deposit",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
wishlist:"love",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
  {id:3,
    shoetype:"Buy Crypto",
    description:"Did a project design today. never thought i would ever develop much patience .",
    Cart:"Add to Cart",
status:"color",
Quickactions:"Sell",
Instock :true,
time:"jan 30, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
wishlist:"love",
price:"-₦10,000",
title:"Veonard Victor",
 icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
 },
  {id:4,
    shoetype:"Save",
    description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
status:"color",
Instock :true,
time:"jan 30, 2024",
sizes:"S",
sizem:"M",
sizel:"L",
Quickactions:"Convert",
wishlist:"love",
price:"₦10,000",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Flutter Deposit",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
{id:5,
  "shoetype":"boot",
description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,
wishlist:"love",
price:"-₦10,000",
icon:"star",
status:"color",
sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Veonard Victor",
time:"jan 30, 2024",
"image":require("../image1/image8-2.webp"),
"image1":require("../image1/image8-2.webp"),
"image2":[require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),
       require("../image1/image8-2.webp"),]
},
{id:6,
  "shoetype":"boot",
  description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
  Cart:"Add to Cart",
  Instock :true,
 wishlist:"love",
price:"₦10,000",
icon:"star",
status:"color",
sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Flutter Deposit",
time:"jan 30, 2024",

 "image":require("../image1/image8-2.webp"),
 "image1":require("../image1/image8-2.webp"),
 "image2":[require("../image1/image8-2.webp"),
 require("../image1/image8-2.webp"),
 require("../image1/image8-2.webp"),]
},

],
 }



  
  export const paidGames = [
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Spider-Man',
      subtitle: 'Marvel',
      isFree: 'No',
      price: '$25.99',
      id: '1',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Battlefield 2042',
      subtitle: 'EA',
      isFree: 'No',
      price: '$19.99',
      id: '2',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Spider-Man: Miles Morales',
      subtitle: 'Marvel',
      isFree: 'No',
      price: '$29.99',
      id: '3',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Halo Infinite',
      subtitle: 'Xbox Game',
      isFree: 'No',
      price: '$24.99',
      id: '4',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Far Cry 6',
      subtitle: 'Ubisoft',
      isFree: 'No',
      price: '$15.99',
      id: '5',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'God of War: Ragnarok',
      subtitle: 'Sony',
      isFree: 'No',
      price: '$25.99',
      id: '6',
    },
  ];
  
  export const freeGames = [
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Altos Odyssey',
      subtitle: 'Noodlecake Studios',
      isFree: 'Yes',
      id: '1',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Asphalt 9',
      subtitle: 'Gameloft',
      isFree: 'Yes',
      id: '2',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Genshin Impact',
      subtitle: 'miHoYo',
      isFree: 'Yes',
      id: '3',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Fortnite',
      subtitle: 'Epic Games',
      isFree: 'Yes',
      id: '4',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Pokémon Unite',
      subtitle: 'The Pokémon Company',
      isFree: 'Yes',
      id: '5',
    },
    {
      poster: require("../image1/image8-2.webp"),
      title: 'Diablo 4',
      subtitle: 'Blizzard Entertainment',
      isFree: 'No',
      id: '6',
    },
  ];















  import { Dimensions } from 'react-native';
import Quickactions from './Utilities/Quickactions';
export const windowWidth = Dimensions.get('window').width;
export const windowHeight = Dimensions.get('window').height;